In [3]:
!pip3 install numpy

In [4]:
import numpy as np

In [5]:
np.__version__

'1.19.2'

In [6]:
#使用List
a = np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
#使用元祖
b = np.array((6,7,8))

In [9]:
b

array([6, 7, 8])

In [10]:
type(a),type(b)

(numpy.ndarray, numpy.ndarray)

In [11]:
c = np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [12]:
# 產生 0 - 9 十個數字元素
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 產生 2, 4, 6, 8 數字元素
# 起始值(結束值),結束值,間隔值
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [14]:
np.arange(-2, 15, 3)

array([-2,  1,  4,  7, 10, 13])

In [15]:
np.arange(1.0, 3.0, 0.5, dtype='float64')

array([1. , 1.5, 2. , 2.5])

In [16]:
a = np.arange(0.13, 0.16, step=0.01)
print("沒有包含結束值：", a)
b = np.arange(0.12, 0.16, step=0.01)
print("包含結束值：", b)

沒有包含結束值： [0.13 0.14 0.15]
包含結束值： [0.12 0.13 0.14 0.15 0.16]


In [17]:
np.arange(0.13,0.16,0.01)

array([0.13, 0.14, 0.15])

In [18]:
np.arange(0.12,0.16,0.01)

array([0.12, 0.13, 0.14, 0.15, 0.16])

In [19]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#                             總數    是否包含結束值   是否顯示間隔值              產生依據的軸

In [22]:
np.linspace(2, 10, num=4, endpoint=False, retstep=False, axis=0)

array([2., 4., 6., 8.])

In [27]:
np.linspace(2, 10, endpoint=True, retstep=True, axis=0)

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]),
 0.16326530612244897)

In [28]:
np.linspace(2, 10, endpoint=True,dtype=int, retstep=True, axis=0)

(array([ 2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,
         4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  7,  7,  7,
         7,  7,  7,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9, 10]),
 0.16326530612244897)

In [33]:
np.linspace(2, 10, num=5,  axis=-1)

array([ 2.,  4.,  6.,  8., 10.])

In [34]:
np.linspace(2, 10, num=5,  axis=0)

array([ 2.,  4.,  6.,  8., 10.])

In [37]:
np.linspace(2, 10, num=5,  axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [38]:
np.linspace(2, 10, num=4, endpoint=False, retstep=True, axis=0)

(array([2., 4., 6., 8.]), 2.0)

In [39]:
# 多維陣列
a = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
2*3
a.shape

(2, 3)

In [44]:
# 三圍陣列
b = np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]]])

In [45]:
b.shape

(2, 4, 3)

In [46]:
np.array([[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
#維度數目
print(a.ndim)
print(b.ndim)

2
3


In [53]:
#維度數目不一致
np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6]]])

<ipython-input-53-4a6bb4c48b2b>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[[1, 2, 3], [4, 5, 6],


array([list([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]),
       list([[1, 2, 3], [4, 5, 6]])], dtype=object)

In [54]:
# 全為0
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# 全為1
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
# 隨機
np.empty((2, 2, 2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 7.31217156e-321],
        [2.05833592e-312, 2.44029516e-312]]])

In [57]:
np.array((2,2,2))

array([2, 2, 2])

In [61]:
np.linspace(0, 20 )

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [76]:
# 設定隨機種子
np.random.seed(0)

In [86]:
#產生數值區間[0, 1) 包含0,不包含1
np.random.rand(2, 3)

array([[0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517]])

In [91]:
#隨機
np.random.randn(2, 3)

array([[-0.31155253,  0.05616534, -1.16514984],
       [ 0.90082649,  0.46566244, -1.53624369]])